#ifndef Analysis_h
#define Analysis_h
/*****************************************************************************
 * Copyright (C) 2009-2016    this file is part of the NPTool Project        *
 *                                                                           *
 * For the licensing terms see $NPTOOL/Licence/NPTool_Licence                *
 * For the list of contributors see $NPTOOL/Licence/Contributors             *
 *****************************************************************************/

/*****************************************************************************
 * Original Author: XAUTHORX  contact address: XMAILX                        *
 *                                                                           *
 * Creation Date  : XMONTHX XYEARX                                           *
 * Last update    :                                                          *
 *---------------------------------------------------------------------------*
 * Decription:                                                               *
 *  This class describe  TiNA analysis project                       *
 *                                                                           *
 *---------------------------------------------------------------------------*
 * Comment:                                                                  *
 *                                                                           *
 *****************************************************************************/

#include <TMath.h>
#include <TRandom3.h>
#include <TVector3.h>

#include <vector>

#include "NPBeam.h"
#include "NPEnergyLoss.h"
#include "NPReaction.h"
#include "NPVAnalysis.h"
#include "RootInput.h"
#include "RootOutput.h"
#include "TCACAOPhysics.h"
#include "TCsIPhysics.h"
#include "TDali2Physics.h"
#include "TDaliPhysics.h"
#include "TGRAPEPhysics.h"
#include "TInitialConditions.h"
#include "TReactionConditions.h"
#include "TTinaPhysics.h"

class Analysis : public NPL::VAnalysis {
 public:
  Analysis();
  ~Analysis();

 public:
  void Init();
  void TreatEvent();
  void End();

  void InitOutputBranch();
  void InitInputBranch();
  void ReInitValue();
  static NPL::VAnalysis* Construct();

  double GetDopplerCorrectedEnergy(double energy, TVector3 position, TVector3 beta);

 private:
  ////////////////////////////////////////////////////////////
  // vertex
  TVector3 vert;
  //
  double BeamReacE;
  // fragment
  TVector3 fragBeta;
  TVector3 fragMom;
  TVector3 TDir;
  ////////////////////////////////////////////////////////////

  ////////////////////////////////////////////////////////////
  // for TiNA
  double Ex, Qval, ELab, ThetaLab, ThetaCM;

  double beamElossT, lightElossT, beamElossW, lightElossW;

  NPL::Reaction myReaction;
  //    Energy loss table: the G4Table are generated by the simulation
  NPL::EnergyLoss* LightTarget;
  NPL::EnergyLoss* BeamTarget;
  NPL::EnergyLoss* LightAl;
  NPL::EnergyLoss* LightSi;
  NPL::EnergyLoss* BeamWindow;
  NPL::EnergyLoss* LightWindow;

  double TargetThickness;
  double WindowsThickness;
  // Beam Energy
  double OriginalBeamEnergy;  // AMEV
  double FinalBeamEnergy;

  // intermediate variable
  TVector3 OriginalBeamDirection;
  TVector3 OriginalBeamImpact;
  TVector3 BeamDirection;
  TVector3 BeamImpact;
  TRandom3 Rand;
  int Run;
  double ThetaNormalTarget;
  double ThetaTiNASurface;
  double Energy;
  double QValue;
  int SquareMultiplicity;
  int TrapMultiplicity;

  double X, Y, Z;
  TVector3 HitPosition;
  TVector3 HitDirection;

  double dE;
  double dTheta;

  // Branches and detectors
  TTinaPhysics* TiNA;
  ////////////////////////////////////////////////////////////

  ////////////////////////////////////////////////////////////
  // for GRAPE
  int grapeM;
  int grapeCN[400], grapeSN[400];
  double grapeE[400], grapeEdc[400], grapeT[400];

  int grapeMadd;
  int grapeCNadd[400], grapeSNadd[400];
  double grapeEadd[400], grapeEdcadd[400], grapeTadd[400];

  std::vector<std::vector<int>> grapeabTable;
  std::vector<int> grapeabN;
  std::vector<double> grapeabE;

  // for DALI
  int daliM;
  int daliCN[400];
  double daliE[400], daliEdc[400], daliT[400];

  int daliMadd;
  int daliCNadd[400];
  double daliEadd[400], daliEdcadd[400], daliTadd[400];

  std::vector<std::vector<int>> daliabTable;
  std::vector<int> daliabN;
  std::vector<double> daliabE;

  // for CACAO
  int cacaoM;
  int cacaoCN[400];
  double cacaoE[400], cacaoEdc[400], cacaoT[400];
  double cacaoR[400], cacaoTheta[400];

  int cacaoMadd;
  int cacaoCNadd[400];
  double cacaoEadd[400], cacaoEdcadd[400], cacaoTadd[400];
  double cacaoRadd[400], cacaoThetaadd[400];

  std::map<int, std::vector<int>> cacaoabTable;
  std::vector<int> cacaoabN;
  std::vector<double> cacaoabE;

  // Branches and detectors
  TGRAPEPhysics* GRAPE;
  TDali2Physics* DALI;
  TCACAOPhysics* CACAO;
  ////////////////////////////////////////////////////////////

  ////////////////////////////////////////////////////////////
  // charge state distribution
  vector<double> csProb;  // probability for full, full+H-like, full+H,He-like,...
  int qState;
  ////////////////////////////////////////////////////////////

  TInitialConditions* myInit;
  TReactionConditions* myReac;
};
#endif
