/vis/open OGL 900x700-0+0
/vis/viewer/set/background white
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/viewpointThetaPhi 70 35
/vis/viewer/zoom 1.2

/vis/drawVolume
/vis/scene/add/axes 0 0 0 50 mm
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/scene/endOfEventAction accumulate 1
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
/tracking/verbose 0

/run/beamOn 1

