#!/bin/bash
set -e

cd "$(dirname "$0")"

mkdir -p generated root/sim root/ana
root -l -b -q make_natural_gamma_hist.C

events="${EVENTS:-10000}"
cone="${CONE_DEG:-4}"
positions="${POSITIONS:--800 -1200 -1600 -2000}"

cat > generated/batch_scan.mac <<EOF
/tracking/verbose 0
/run/beamOn ${events}
EOF

for x in ${positions}; do
  tag="x${x}"
  reaction="generated/background_plus_co60_${tag}.reaction"
  output="background_plus_co60_${tag}.root"

  cat > "${reaction}" <<EOF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Generated by run_co60_position_scan.sh.
% Natural background at x=-400 mm plus Co-60 lines at x=${x} mm.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Isotropic
 EnergyLow= 0.05 MeV
 EnergyHigh= 3.0 MeV
 EnergyDistribution= FromHisto
 EnergyDistributionHist= natural_gamma_lines.root h_gamma
 HalfOpenAngleMin= 0 deg
 HalfOpenAngleMax= 8 deg
 Direction= x
 x0= -400 mm
 y0= 0 mm
 z0= 0 mm
 Particle= gamma
 Multiplicity= 1

Isotropic
 EnergyLow= 1.173228 MeV
 EnergyHigh= 1.173228 MeV
 HalfOpenAngleMin= 0 deg
 HalfOpenAngleMax= ${cone} deg
 Direction= x
 x0= ${x} mm
 y0= 0 mm
 z0= 0 mm
 Particle= gamma
 Multiplicity= 1

Isotropic
 EnergyLow= 1.332492 MeV
 EnergyHigh= 1.332492 MeV
 HalfOpenAngleMin= 0 deg
 HalfOpenAngleMax= ${cone} deg
 Direction= x
 x0= ${x} mm
 y0= 0 mm
 z0= 0 mm
 Particle= gamma
 Multiplicity= 1
EOF

  npsimulation -D hpge.detector -E "${reaction}" -B generated/batch_scan.mac -O "${output}" -N
  root -l -b -q "plot_hpge_energy.C(\"root/sim/${output}\",\"root/ana/background_plus_co60_${tag}\")"
done

root -l -b -q 'plot_hpge_scan_overlay.C()'
