/vis/open OGL 800x800-0+0
/vis/scene/add/axes 0 0 0 300 mm
/vis/drawVolume
/vis/viewer/flush
/vis/viewer/set/background white
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/viewpointThetaPhi 80 45
/vis/viewer/zoom 0.8
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/scene/endOfEventAction accumulate
/vis/geometry/set/visibility logicWorld 0 false
/vis/viewer/set/autoRefresh true
/tracking/verbose 1
/vis/verbose warnings
/run/beamOn 1
